/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view.admin;

import com.controller.AccountController;
import com.controller.HoadonController;
import com.model.AccountModel;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Account_admin extends javax.swing.JFrame {

    private String idxeclick = "";
    private int rowclick = -1;

    public Account_admin() {
        initComponents();
        khoitaobang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        butthoat = new javax.swing.JButton();
        buthoadon = new javax.swing.JButton();
        buthome = new javax.swing.JButton();
        butkhoxe = new javax.swing.JButton();
        buttaikhoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pantaikhoan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ndtimkiem = new javax.swing.JTextField();
        timkiem = new javax.swing.JButton();
        sxtheo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangchinh = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tktheo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        them = new javax.swing.JButton();
        butcapnhap = new javax.swing.JButton();
        butxoa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lammoi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ttk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tht = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tvt = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ttt = new javax.swing.JComboBox<>();
        tmk = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        butthoat.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        butthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/icon/Exit_40.png"))); // NOI18N
        butthoat.setText("Thoát");
        butthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthoatActionPerformed(evt);
            }
        });

        buthoadon.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        buthoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/icon/hoa_don.png"))); // NOI18N
        buthoadon.setText("Đơn hàng");
        buthoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buthoadonActionPerformed(evt);
            }
        });

        buthome.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        buthome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/icon/home_40.png"))); // NOI18N
        buthome.setText("Trang chủ");
        buthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buthomeActionPerformed(evt);
            }
        });

        butkhoxe.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        butkhoxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/icon/kho_xe.png"))); // NOI18N
        butkhoxe.setText("Kho xe");
        butkhoxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butkhoxeMouseClicked(evt);
            }
        });
        butkhoxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butkhoxeActionPerformed(evt);
            }
        });

        buttaikhoa.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        buttaikhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/icon/tai_khoan.png"))); // NOI18N
        buttaikhoa.setText("Tài khoản");
        buttaikhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttaikhoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buthoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buthome, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(butkhoxe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttaikhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(butthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(buthome, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(buthoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(buttaikhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(butkhoxe, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(butthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("CHƯƠNG TRÌNH QUẢN LÝ PHƯƠNG TIỆN GIAO THÔNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(385, 385, 385))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pantaikhoan.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("Quản lý tài khoản");

        ndtimkiem.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ndtimkiemInputMethodTextChanged(evt);
            }
        });
        ndtimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndtimkiemActionPerformed(evt);
            }
        });

        timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/icon/search_24.png"))); // NOI18N
        timkiem.setText("Tìm kiếm");
        timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemActionPerformed(evt);
            }
        });

        sxtheo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        sxtheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tài khoản A-Z", "Họ tên A-Z" }));
        sxtheo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sxtheoActionPerformed(evt);
            }
        });

        bangchinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        bangchinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Tài khoản", "Mật khẩu", "Họ tên", "Vai trò", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bangchinh);
        bangchinh.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Tìm kiếm theo");

        tktheo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tktheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tài khoản", "Họ tên", "Vai trò", "Trạng thái" }));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Sắp xếp theo");

        them.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/icon/them.png"))); // NOI18N
        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        butcapnhap.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        butcapnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/icon/cap_nhat_24.png"))); // NOI18N
        butcapnhap.setText("Cập nhật");
        butcapnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butcapnhapActionPerformed(evt);
            }
        });

        butxoa.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        butxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/icon/xoa.png"))); // NOI18N
        butxoa.setText("Xóa");
        butxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lammoi.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/icon/lam_moi_24.png"))); // NOI18N
        lammoi.setText("Làm mới");
        lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lammoiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Tài khoản");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Mật khẩu");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Họ tên");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Vai trò");

        tvt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "MEMBER" }));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText("Trạng thái");

        ttt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "DISABLE" }));
        ttt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pantaikhoanLayout = new javax.swing.GroupLayout(pantaikhoan);
        pantaikhoan.setLayout(pantaikhoanLayout);
        pantaikhoanLayout.setHorizontalGroup(
            pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantaikhoanLayout.createSequentialGroup()
                .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantaikhoanLayout.createSequentialGroup()
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pantaikhoanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pantaikhoanLayout.createSequentialGroup()
                                .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butcapnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pantaikhoanLayout.createSequentialGroup()
                                .addComponent(butxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pantaikhoanLayout.createSequentialGroup()
                                .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tht, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(tmk)
                                    .addComponent(ttk)
                                    .addComponent(tvt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ttt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantaikhoanLayout.createSequentialGroup()
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pantaikhoanLayout.createSequentialGroup()
                                .addComponent(ndtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantaikhoanLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tktheo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(333, 333, 333)))
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sxtheo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pantaikhoanLayout.setVerticalGroup(
            pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantaikhoanLayout.createSequentialGroup()
                .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantaikhoanLayout.createSequentialGroup()
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantaikhoanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tktheo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pantaikhoanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ndtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sxtheo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(pantaikhoanLayout.createSequentialGroup()
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pantaikhoanLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ttk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pantaikhoanLayout.createSequentialGroup()
                                        .addComponent(tmk)
                                        .addGap(8, 8, 8))))
                            .addGroup(pantaikhoanLayout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tht, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tvt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butcapnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pantaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pantaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pantaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butkhoxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butkhoxeMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_butkhoxeMouseClicked

    private void timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemActionPerformed
        idxeclick = "";
        rowclick = -1;
        String noidung = ndtimkiem.getText();
        String tkt = String.valueOf(tktheo.getSelectedItem());
        String timkiemtheo = "username";
        if (tkt.equals("Họ tên")) {
            timkiemtheo = "displayname";
        }
        if (tkt.equals("Vai trò")) {
            timkiemtheo = "role";
        }
        if (tkt.equals("Trạng thái")) {
            timkiemtheo = "status";
        }
        if (noidung.equals("") == false) {
            System.out.println(noidung + "\t" + timkiemtheo);
            bangTimKiem(noidung, timkiemtheo);
        } else {
            khoitaobang();
        }
    }//GEN-LAST:event_timkiemActionPerformed

    private void butkhoxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butkhoxeActionPerformed
        dispose();
        JFrame x = new Kho_xe();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
    }//GEN-LAST:event_butkhoxeActionPerformed

    private void buthoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buthoadonActionPerformed
        dispose();
        JFrame x = new Don_hang();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
    }//GEN-LAST:event_buthoadonActionPerformed

    private void butthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthoatActionPerformed
        dispose();
    }//GEN-LAST:event_butthoatActionPerformed

    private void butxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butxoaActionPerformed
        if(idxeclick.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn cần click vào tài khoản cần xóa");
            return;
        }
        String taikhoan = idxeclick;
        if (AccountController.checkDkUser(taikhoan) == false) {
            JOptionPane.showMessageDialog(null, "Tài khoản cần xóa không tồn tại");
        } else {
            int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn xóa tài khoản: " + taikhoan);
            if (x == 0) {
                if (AccountController.deleteAccount(taikhoan)) {
                    JOptionPane.showMessageDialog(null, "Đã xóa thành công tài khoản " + taikhoan);
                    khoitaobang();
                } else {
                    JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra trong hệ thống");
                }
            }

        }
    }//GEN-LAST:event_butxoaActionPerformed

    private void buttaikhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttaikhoaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_buttaikhoaActionPerformed

    private void tttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tttActionPerformed

    private void buthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buthomeActionPerformed
        dispose();
        JFrame x = new Home_admin();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
    }//GEN-LAST:event_buthomeActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        String vaitro = tvt.getSelectedItem().toString();
        String trangthai = ttt.getSelectedItem().toString();
        String taikhoan = ttk.getText();
        String matkhau = tmk.getText();
        String hoten = tht.getText();
        if (hoten.equals("") || taikhoan.equals("") || matkhau.equals("")) {
            JOptionPane.showMessageDialog(null, "Cần điền đầy đủ thông tin");
        } else {
            if (AccountController.checkDkUser(taikhoan)) {
                JOptionPane.showMessageDialog(null, "Tài khoản đã tồn tại");
            }
            if (AccountController.luuAccount(taikhoan, matkhau, hoten, vaitro, trangthai)) {
                JOptionPane.showMessageDialog(null, "Đã thêm tài khoản thành công");
                khoitaobang();
            }
        }

    }//GEN-LAST:event_themActionPerformed

    private void lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lammoiActionPerformed
        khoitaobang();
        ttk.setText("");
        tht.setText("");
        tmk.setText("");
        ndtimkiem.setText("");
    }//GEN-LAST:event_lammoiActionPerformed

    private void butcapnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butcapnhapActionPerformed
        if(rowclick == -1) {
            JOptionPane.showMessageDialog(null, "Bạn cần click vào dòng cần cập nhật");
            return;
        }
        String taikhoan = (String)bangchinh.getValueAt(rowclick, 0);
        String matkhau = (String)bangchinh.getValueAt(rowclick, 1);
        String hoten = (String)bangchinh.getValueAt(rowclick, 2);
        String vaitro = (String)bangchinh.getValueAt(rowclick, 3);
        String trangthai = (String)bangchinh.getValueAt(rowclick, 4);
        if(taikhoan.equals("") || matkhau.equals("") || hoten.equals("") || vaitro.equals("") || trangthai.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn cần điền đầy đủ thông tin trước khi cập nhật");
            return;
        }
        if(taikhoan.equals(idxeclick)==false) {
            JOptionPane.showMessageDialog(null, "Bạn không thể thay đổi tên tài khoản");
            return;
        }
        if(AccountController.updateAccount(taikhoan, matkhau, hoten, vaitro, trangthai)) {
            JOptionPane.showMessageDialog(null, "Đã cập nhật thành công");
            khoitaobang();
        }
        else {
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi cập nhật");
        }
//        String vaitro = tvt.getSelectedItem().toString();
//        String trangthai = ttt.getSelectedItem().toString();
//        String taikhoan = ttk.getText();
//        String matkhau = tmk.getText();
//        String hoten = tht.getText();
//        if (hoten.equals("") || taikhoan.equals("") || matkhau.equals("")) {
//            JOptionPane.showMessageDialog(null, "Cần điền đầy đủ thông tin");
//        } else {
//            if (AccountController.checkDkUser(taikhoan) == false) {
//                JOptionPane.showMessageDialog(null, "Tài khoản này chưa tồn tại trong hệ thống!!!");
//            } else {
//                if (matkhau.length() < 6) {
//                    JOptionPane.showMessageDialog(null, "Mật khẩu cần có độ dài từ 6 ký tự trở lên");
//                } else {
//                    int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn cập nhật lại tài khoản này không?");
//                    if (x == 0) {
//                        if (AccountController.updateAccount(taikhoan, matkhau, hoten, vaitro, trangthai)) {
//                            JOptionPane.showMessageDialog(null, "Đã cập nhật thành công!!!");
//                            khoitaobang();
//                        } else {
//                            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi cập nhật");
//                        }
//                    }
//                }
//
//            }
//        }
    }//GEN-LAST:event_butcapnhapActionPerformed

    private void ndtimkiemInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ndtimkiemInputMethodTextChanged

    }//GEN-LAST:event_ndtimkiemInputMethodTextChanged

    private void ndtimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndtimkiemActionPerformed

    }//GEN-LAST:event_ndtimkiemActionPerformed

    private void sxtheoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sxtheoActionPerformed
        idxeclick = "";
        rowclick = -1;
        String ndsort = String.valueOf(sxtheo.getSelectedItem());
        if (ndsort.contains("Tài khoản")) {
            ndsort = "username";
        }
        if (ndsort.contains("Họ tên")) {
            ndsort = "displayname";
        }
        bangSapxep(ndsort);
    }//GEN-LAST:event_sxtheoActionPerformed

    // ----------Phần này sử lý nội dung ------------------
    public void khoitaobang() {
        String[] column = {"Tài khoản", "Mật khẩu", "Họ tên", "Vai trò", "Trạng thái"};
        DefaultTableModel model = new DefaultTableModel();
        List<AccountModel> list = new ArrayList<>();
        list = AccountController.getAccount();
        System.out.println(list.size());
        for (String x : column) {
            model.addColumn(x);
        }
        for (AccountModel t : list) {
            Object[] x = {t.getUserName(), t.getPassword(), t.getDisplayName(), t.getRole(), t.getStatus()};
            model.addRow(x);
        }
        bangchinh.setModel(model);
        bangchinh.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Kiểm tra xem có phải sự kiện nhấp chuột hay không
                if (e.getValueIsAdjusting()) {
                    // Lấy chỉ số hàng đã chọn
                    int selectedRow = bangchinh.getSelectedRow();
                    // In ra thông tin của hàng đã chọn
                    if (selectedRow != -1) {
                        idxeclick = (String) bangchinh.getValueAt(selectedRow, 0);
//                        System.out.println(idxeclick);
                        rowclick = selectedRow;
                    }

                }
            }
        });
    }

    public void bangTimKiem(String nd, String tktheo) {
        String[] column = {"Tài khoản", "Mật khẩu", "Họ tên", "Vai trò", "Trạng thái"};
        DefaultTableModel model = new DefaultTableModel();
        List<AccountModel> list = new ArrayList<>();
        list = AccountController.getAccountTheoyc(nd, tktheo);
        System.out.println(list.size());
        for (String x : column) {
            model.addColumn(x);
        }
        for (AccountModel t : list) {
            Object[] x = {t.getUserName(), t.getPassword(), t.getDisplayName(), t.getRole(), t.getStatus()};
            model.addRow(x);
        }
        bangchinh.setModel(model);
    }

    public void bangSapxep(String ndsort) {
        String[] column = {"Tài khoản", "Mật khẩu", "Họ tên", "Vai trò", "Trạng thái"};
        DefaultTableModel model = new DefaultTableModel();
        List<AccountModel> list = new ArrayList<>();
        list = AccountController.getAccountBysort(ndsort);
        System.out.println(list.size());
        for (String x : column) {
            model.addColumn(x);
        }
        for (AccountModel t : list) {
            Object[] x = {t.getUserName(), t.getPassword(), t.getDisplayName(), t.getRole(), t.getStatus()};
            model.addRow(x);
        }
        bangchinh.setModel(model);
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame x = new Account_admin();
                x.setLocationRelativeTo(null);
                x.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangchinh;
    private javax.swing.JButton butcapnhap;
    private javax.swing.JButton buthoadon;
    private javax.swing.JButton buthome;
    private javax.swing.JButton butkhoxe;
    private javax.swing.JButton buttaikhoa;
    private javax.swing.JButton butthoat;
    private javax.swing.JButton butxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lammoi;
    private javax.swing.JTextField ndtimkiem;
    private javax.swing.JPanel pantaikhoan;
    private javax.swing.JComboBox<String> sxtheo;
    private javax.swing.JButton them;
    private javax.swing.JTextField tht;
    private javax.swing.JButton timkiem;
    private javax.swing.JComboBox<String> tktheo;
    private javax.swing.JTextField tmk;
    private javax.swing.JTextField ttk;
    private javax.swing.JComboBox<String> ttt;
    private javax.swing.JComboBox<String> tvt;
    // End of variables declaration//GEN-END:variables
}
